development:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: personal_website_development
  
test:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: personal_website_test

production:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: personal_website_production